pages:
  image: node
  before_script:
    - pwd
  script:
    - cd client
    - npm --version
    - date
    - time yarn install
    - date
    - time yarn run generate
    - date
    - du -sh public/
    - mv public ../public
    - ls -a
    - pwd
    - cd ..
    - ls -a
    - pwd
  artifacts:
    paths:
      - public

test:client:
   image: angular/ngcontainer
   script:
     - cd client
     - yarn install 
     - xvfb-run -a yarn test
