image: node

cache:
  paths:
    - client/node_modules/

pages:
  script:
    - cd client
    - npm --version
    - date
    - yarn install
    - date
    - yarn run generate
    - date
    - du -sh public/
    - ls -a

  artifacts:
    paths:
      - client/public
