version: 2
jobs:
  build:
    working_directory: ~/ng
    docker:
      - image: angular/ngcontainer:0.2.0
    steps:
      - checkout
      - run: yarn
      - run: ls -a && cd /home/circleci/ng/client && yarn run 
      - run: cd /home/circleci/ng/client && yarn run build
      - run: cd /home/circleci/ng/client && xvfb-run -a yarn test