version: 2
jobs:
  build:
    working_directory: ~/ng
    docker:
      - image: angular/ngcontainer:0.2.0
    steps:
      - checkout
      - run: pwd 
      - run: ls -a 
      - run: cd client
      - run: ls -a 
      - run: yarn
      - run: yarn run format:enforce
      - run: yarn run build
      - run: xvfb-run -a yarn test